version: '3.5'

services:

    nginx:
        container_name: ${NGINX_CONTAINER_NAME}
        image: ${NGINX_CONTAINER_NAME}
        build:
            context: ./docker/nginx
            args:
                UID: $UID
                NGINX_VERSION: $NGINX_VERSION
        ports:
            - "8005:80"
        volumes:
                - ./public:/var/www/public:cached
        depends_on:
            - php

    php:
        container_name: ${PHP_CONTAINER_NAME}
        image: ${PHP_CONTAINER_NAME}
        build:
            context: docker/php
            args:
                UID: $UID
                SYMFONY_VERSION: $SYMFONY_VERSION
                PHP_VERSION: $PHP_VERSION
        environment:
            XDEBUG_CONFIG: "mode=debug client_host=host.docker.internal client_port=9003 start_with_request=yes"
            PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated